### ISSUE TITLE
Clark release branch

### ISSUE THREAD

**Issue by rabih** [MotorolaMobilityLLC/system-core#2]
@tags07 Do you plan on releasing a version for the clark on the system-core repository? I see the lux is missing as well.

**Comment by tags07** [comment]
i'll check.. not sure if its the case of no changes from an existing commit..in which case we should atleast apply the tag.

**Comment by tags07** [comment]
@somcom3x Looks like Moto X Gen3 tag is listed here: https://github.com/MotorolaMobilityLLC/system-core/releases/tag/MMI-LPH23.116-18.1

and Moto X Play is listed here: https://github.com/MotorolaMobilityLLC/system-core/releases/tag/MMI-LPD23.118-12

**Comment by vinimed** [comment]
Ticket is too old. If you are still interested, please re-open the issue.
