### ISSUE TITLE
Can I find a windows USB debug driver in this repo?

### ISSUE THREAD

**Issue by plato-cambrian** [MotorolaMobilityLLC/system-core#4]
Hi, I am new to Android development and I would like to use my Moto E 2nd gen with ADB. The default Windows 7 driver doesn't work with USB debugging.
Google's [OEM Hardware Development Drivers](https://developer.android.com/tools/extras/oem-usb.html#Drivers) page links to [developer.motorola.com](http://developer.motorola.com/docstools/USB_Drivers/) where I am supposed to find a USB debugging driver. Unfortunately the link redirects to a page that doesn't have the driver.

Any chance this repo contains a copy of the driver?
If not, anyone know how I can report the missing file to the developer.motorola.com web development team?
I would rather have an official link than run a random driver from Google.

**Comment by vinimed** [comment]
Ticket is too old. If you are still interested, please re-open the issue.
